---
link-external-newwindow: true
---

<!-- 
<center><a href="#" class="btn btn-info btn-lg" role="button"><i class="bi bi-calendar-check"></i>（受付終了）&nbsp;&nbsp;&nbsp;オフィスアワーの予約</a></center><br/>

<center><a href="https://www.jaysong.net/garage/2025/OH/reservation.html" class="btn btn-info btn-lg" target="_blank" role="button"><i class="bi bi-calendar-check"></i>&nbsp;&nbsp;&nbsp;オフィスアワーの予約</a></center><br/>
-->

```{r}
#| include: false
ff_ver <- system('plutil -extract "CFBundleShortVersionString" binary1 /Applications/Firefox.app/Contents/Info.plist -o -', intern = TRUE) |>
  stringr::str_extract("[0-9]+\\.[0-9]+.+") |>
  stringr::str_replace("\b", "")

rs_ver1 <- system('plutil -extract "CFBundleShortVersionString" binary1 /Applications/RStudio.app/Contents/Info.plist -o -', intern = TRUE) |>
  stringr::str_replace("-daily", "") |>
  stringr::str_extract("202[0-9]\\.[0-9]+\\.[0-9]+\\+[0-9]+")
```

:::{.callout-important}
## 2026年度入ゼミについて

　ゼミ応募に関する情報は「[応募 > 応募方法](entry/entry.qmd)」をご参照ください。
:::

関西大学総合情報学部「専門演習＆卒業研究（宋）」のホームページです。スマホ環境の方は画面左上の「$\equiv$」ボタンをタップしてください。

<!--
:::{.callout-important}
## 2025年度入ゼミについて

　2025年度の入ゼミは募集終了しました。
:::
-->

```{r}
#| eval: false
#| echo: false
pacman::p_load(tidyverse, DT)
tibble(Date  = c("9/25", 
                 "9/29", "9/29", "9/29",
                 "10/3", "10/3",
                 "10/7", "10/7", 
                 "10/8", "10/8",
                 "10/14"),
       Week  = c("木", 
                 "月", "月", "月", 
                 "金", "金",
                 "火", "火",
                 "水", "水",
                 "火"),
       Time1 = c("3限", 
                 "昼休み", "3限", "4限", 
                 "3限", "4限", 
                 "昼休み", "3限",
                 "3限", "4限",
                 "3限"
                 ),
       Place = c("TA227",
                 "TA227", "TA227", "TA227",
                 "TA227", "TA227", 
                 "TA227", "TA227", 
                 "TA227", "TA227",
                 "TA227"),
       Etc   = c("",
                 "最大3人", "", "", 
                 "", "", 
                 "最大3人", "", 
                 "", "",
                 "")) |> 
   mutate(Date  = paste0("2024/", Date),
          Date  = as.Date(Date),
          Week  = factor(Week, levels = c("月", "火", "水", "木", "金")),
          Time1 = factor(Time1, levels = c("2限", "昼休み", "3限", "4限")),
          Time2 = case_when(Time1 == "2限" ~ "10:40",
                            Time1 == "3限" ~ "13:00",
                            Time1 == "4限" ~ "14:40",
                            TRUE           ~ "12:15"),
          Place = factor(Place, levels = c("TA227", "TK108", "Zoom"))) |> 
   relocate(Time2, .after = Time1) |> 
   datatable(filter   = "top",
             colnames = c("日付", "曜日", "時間", "開始時間", "場所", "備考"),
             options  = list(autoWidth  = TRUE,
                             paging     = FALSE,
                             searching  = FALSE,
                             ordering   = FALSE))
```

:::{.callout-note}
## ページ情報

* 最終更新日: `r format(Sys.Date(), "%Y年%m月%d日")`
* 開発環境
   * `r sessionInfo()$running`
   * Firefox `r ff_ver`
   * `r version$version.string`
   * RStudio `r rs_ver1`
   * Quarto `r quarto::quarto_inspect()$quarto$version`
   * R package {quarto} `r packageVersion("quarto")`
:::
