---
title: "担当教員について"
date-modified: "`r Sys.Date()`"
toc: true
link-external-newwindow: true
---

```{r}
#| include: false
```

<center><a href="https://www.jaysong.net/" class="btn btn-info btn-lg" target="_blank" role="button"><i class="bi bi-person-circle"></i>&nbsp;&nbsp;&nbsp;担当教員のホームページへ</a></center>

## 基本情報

* 宋 財泫（そん じぇひょん; SONG JAEHYUN; 송 재현）
   * 韓国（ソウル）出身
* 博士（政治学）
* 専門領域
   * 政治行動論（選挙研究）
   * 政治学方法論

## 紹介

　私は政治行動論と政治学方法論を専門としています。政治行動論は政治における様々な主体（有権者、市民、政治家、官僚、マスコミ、若者、ネット民など）の行動や意識を観察したり、因果関係を分析する学問ですが、私の主な観察対象は有権者です。この観察や分析を支えるのが政治学方法論です。観察には観察済み（=既に公開されている）のデータを使うこともあれば、自分の問いを検証するために世論調査などを通じて観察する場合もあります。

　要するに私の仕事は**政治的現象をデータを用いて分析する**ことです。私の研究活動に興味のある方は[個人ホームページ](https://www.jaysong.net/)の[Researchページ](https://www.jaysong.net/research/index.qmd)、使用するツールに興味のある方は[Tutorialページ](https://www.jaysong.net/tutorial/index.qmd)を参照してください。とりわけ、ゼミの担当教員がどのような研究をする人かを知ることは重要であり、研究の履歴を見ることをおすすめします（本ゼミに限らず、全ゼミに共通します）。

　趣味はグルメとゲームです。麺類（とりわけラーメン）が好きですが、最近は少し控えております。ゲームは最近、Final Fantasy XIV（Masamune@Mana）とFinal Fantasy XVIをプレイしております。

## 略歴

#### 職歴

* 2022年度〜：[関西大学](https://www.kansai-u.ac.jp/)[総合情報学部](https://www.kansai-u.ac.jp/Fc_inf/)　准教授
* 2021年度：[同志社大学](https://www.doshisha.ac.jp/)[文化情報学部](https://www.cis.doshisha.ac.jp/)　助教
* 2019〜2020年度：[早稲田大学](https://www.waseda.jp/)[高等研究所](https://www.waseda.jp/inst/wias/)　講師

#### 学歴

* 2015〜2017年度：[神戸大学](http://www.kobe-u.ac.jp/)[法学研究科](http://www.law.kobe-u.ac.jp/)　博士課程後期課程
   * 博士（政治学）
      * 博士論文：「争点空間の歪みと有権者の選択―伸縮近接性モデルによる争点投票理論の統合―」
* 2012〜2014年度：[神戸大学](http://www.kobe-u.ac.jp/)[法学研究科](http://www.law.kobe-u.ac.jp/)　博士課程前期課程
   * 修士（政治学）
      * 修士論文：「韓国は地域主義を超えられるか―選挙公約の役割の実証分析―」
   * 2012年度：語学留学（アメリカ）
* 2006〜2011年度：[慶應義塾大学](https://www.keio.ac.jp/ja/)[法学部政治学科](https://www.law.keio.ac.jp/)
   * 学士（法学）
   * 2009〜2010年度：兵役による休学
* 2002〜2004年度：[東国大学校師範大学附属高等学校](https://ddbk.sen.hs.kr/)

## 連絡先

* E-mail: song<i class="bi bi-at"></i>kansai-u.ac.jp
* Homepage: <https://www.jaysong.net>
* 個人研究室：TA227（A棟2階）
   * 研究室を訪問される際は、必ず事前にメール等で予約してください。