---
title: "宋ゼミを志望する皆様へ"
date-modified: "`r Sys.Date()`"
link-external-newwindow: true
toc: true
---

<center><a href="https://airrsv.net/song2022/calendar" class="btn btn-info btn-lg" target="_blank" role="button"><i class="bi bi-calendar-check"></i>&nbsp;&nbsp;&nbsp;オフィスアワーの予約</a></center>

:::{.callout-important}
## 合同オフィスアワーに参加された方へ

　合同オフィスアワーに参加された方でも、本ゼミに申し込む予定のある方は個別オフィスアワーにもご参加ください。
:::

:::{.callout-important}
## 予約システムのメンテナンスについて

　2023年9月28日（木）午前0:00頃～午前8：00頃まで、予約システムのメンテナンスのため利用ができません。
:::

## オフィスアワー

本ゼミのオフィスアワーは**予約制**です。

* **場所:** 宋の個人研究室（TA227）
   * A棟2階にあります。
   * 一部の時間帯はゼミ教室（TK108）で行います。
   * 参加者の数に応じて、ゼミ教室（TK108）へ変更される場合があります。変更が生じる場合は場所移動の旨を個人研究室のドアに貼ります。
* **予約方法:** 専用サイトで予約してください。<span class="jay_btn">[予約ページへ](https://airrsv.net/song2022/calendar)</span>
   * オフィスアワーには参加したいが、<u>希望する時間帯が掲載されていない場合</u>はメールでお問い合わせください（<song@kansai-u.ac.jp>）。適宜、枠を追加するか個別に対応します。
   * <u>メールでの予約受け付けも可能</u>です。希望する日付・時間帯を下記のリストから選び、メールでお知らせください。
* **注意事項** 
   * 1時間前までに予約者がゼロの場合、当該時間帯は不在の可能性があります。「行くかどうか迷っている」、「行けたらいく」の場合でもとりあえず予約をしてください。予約はいつでもキャンセル可能です（直前でもキャンセル可）。
   * オフィスアワーは原則、対面で行われますが、**非対面形式のオフィスアワー**も可能です。新型コロナの感染、もしくは濃厚接触により対面での参加が困難な場合はメールでお問い合わせください。
   * 希望者の数に応じてオフィスアワーの枠が増える可能性があります（減ることはございません）。最新情報は本ページに掲載します。
   * **合同オフィスアワーに参加された方でも、本ゼミに申し込む予定のある方は個別オフィスアワーにもご参加ください。**

```{r}
#| echo: false
pacman::p_load(tidyverse, DT)
tibble(Date  = c("9/28", "10/2", "10/3", "10/5", "10/6", 
                 "10/11", "10/11", "10/13", "10/16", "10/17"),
       Week  = c("木", "月", "火", "木", "金", 
                 "水", "水", "金", "月", "火"),
       Time1 = c("昼休み", "3限", "2限", "3限", "昼休み", 
                 "2限", "3限", "4限", "昼休み", "4限"),
       Place = c("TA227", "TA227", "TA227", "TK108", "TA227", 
                 "TA227", "TA227", "TA227", "TA227", "TA227"),
       Etc   = c()) |> 
   mutate(Date  = paste0("2023/", Date),
          Date  = as.Date(Date),
          Week  = factor(Week, levels = c("月", "火", "水", "木", "金")),
          Time1 = factor(Time1, levels = c("2限", "昼休み", "3限", "4限")),
          Time2 = case_when(Time1 == "2限" ~ "10:40",
                            Time1 == "3限" ~ "13:00",
                            Time1 == "4限" ~ "14:40",
                            TRUE           ~ "12:15"),
          Place = factor(Place, levels = c("TA227", "TK108")),
          Etc   = if_else(Place == "TK108", "ゼミ室", "")) |> 
   relocate(Time2, .after = Time1) |> 
   datatable(filter   = "top",
             colnames = c("日付", "曜日", "時間", "開始時間", "場所", "備考"),
             options  = list(autoWidth  = TRUE,
                             paging     = FALSE,
                             searching  = FALSE,
                             ordering   = FALSE))
```

## 応募者への課題

:::{.callout-important}
## 第2希望でも【応募者への課題】があります！

* **第1希望**として応募する場合は【志望理由】、【課題1】、【課題2】全てを、それぞれの記入欄に記入し、提出してください。
* **第2希望**として応募する場合は課題を記入する欄がないため、**志望理由の箇所に【志望理由】+【課題1】+【課題2】全て**を書いてください。
:::

1. **【志望理由】**志望理由（500字以上）
   * 本ページの「ゼミ紹介」をお読みの上、**本ゼミに応募する理由、きっかけ、抱負など**を自由に書いてください。
      * どの点に惹かれたか、
      * 自分がどの点に合致しているか、
      * 現在は合致していないが、こういう人になりたいと思ったか、
      * その他いろいろ
   * 模範解答、テンプレなどは存在しません。ネットで検索すると志望理由書のテンプレ、雛形が見られますが、こちらは使わず、自分の考えを述べてください。
2. **【課題1】**これまで最も熱心に取り組んだ授業の科目名（3〜5つ）
   * 科目名のみで結構です。
   * 最も成績が良かった授業ではなく、**最も楽しかった授業・前のめりで取り組んだ授業**を挙げてください。
3. **【課題2】**現時点における取り組みたい卒業研究のテーマ（300字以上）
   * **個人的に興味深いと思う社会現象の概要と着想に至った経緯、背景**などを述べてください。
   * 卒業研究の**テーマは配属後、いつでも変更可能**です。