---
title: "おすすめの資料"
date-modified: "`r Sys.Date()`"
---

```{r}
#| include: false
```

以下のリストはほんの一部です。これから少しずつ追加しておきます。以下の資料をゼミ中に全て読むことはできませんが、何冊かピックアップして輪読する予定です。【】が付いている書籍は当該年度に使用した資料です。

#### リサーチデザイン

* 【2022】[久米郁男. 2013. 『原因を推論する』有斐閣](https://www.amazon.co.jp/dp/4641149070/)
* 【2022・2023・2024・2025】[浅野正彦・矢内勇生. 2018. 『Rによる計量政治学』オーム社](https://www.amazon.co.jp/dp/4274223132/)（第1〜3章）
* [G.キング・R.O.コヘイン・S.ヴァーバ (著), 真渕勝 (訳). 2004. 『社会科学のリサーチ・デザイン―定性的研究における科学的推論』勁草書房](https://www.amazon.co.jp/dp/4326301503/) (2021年、待望の新版が出ました。)
* [伊藤修一郎. 2011.『政策リサーチ入門―仮説検証による問題解決の技法』東京大学出版会](https://www.amazon.co.jp/dp/413032215X/)
* [野村康. 2017.『 社会科学の考え方―認識論、リサーチ・デザイン、手法―』名古屋大学出版会](https://www.amazon.co.j/dp/4815808767/)

#### Rの使い方

* [Hadley Wickham・Garrett Grolemund (著), 黒川利明 (訳). 2017『Rではじめるデータサイエンス』オライリージャパン](https://www.amazon.co.jp/dp/487311814X/) (原著はウェブで読めます (<https://r4ds.had.co.nz/>))
* [松村優哉・湯谷啓明・紀ノ定保礼・前田和寛. 2021. 『RユーザのためのRStudio[実践]入門〜tidyverseによるモダンな分析フローの世界（改訂2版）』技術評論社](https://www.amazon.co.jp/dp/B095W5G8KB/)
* [宋財泫・矢内勇生『私たちのR: ベストプラクティスの探求』web-book.](https://www.jaysong.net/RBook/)
* [無料で読めるR教材のリスト](https://www.jaysong.net/post/free_r_book/)

#### R + データ分析

* 【2022・2023】[浅野正彦・矢内勇生. 2018. 『Rによる計量政治学』オーム社](https://www.amazon.co.jp/dp/4274223132/)（第4章〜）
* [今井耕介 (著), 粕谷祐子・原田勝孝・久保浩樹 (訳). 2018. 『社会科学のためのデータ分析入門 (上/下)』岩波書店](https://www.amazon.co.jp/dp/400061245X/)
* 【2025】[エレーナ ローデ・今井耕介 (著), 原田勝孝 (訳). 2025 『新・社会科学のためのデータ分析入門 導入編』岩波書店](https://amzn.asia/d/5SrFV8M )
* [飯田健. 2013. 『計量政治分析』共立出版](https://www.amazon.co.jp/dp/4320019245)

#### 因果推論

* [伊藤公一朗. 2017. 『データ分析の力』光文社新書](https://www.amazon.co.jp/dp/4334039863/)
* 【2024・2025】[中室牧子・津川友介. 2017.『「原因と結果」の経済学―データから真実を見抜く思考法』ダイヤモンド社](https://www.amazon.co.jp/dp/447803947X/)
* [安井翔太. 2020. 『効果検証入門』技術評論社](https://www.amazon.co.jp/dp/4297111179/)
* 【2022・2023】[松林哲也. 2022. 『政治学と因果推論』岩波書店](https://www.amazon.co.jp/dp/4000269992/)
* [高橋将宜. 2022. 『統計的因果推論の理論と実装』共立出版](https://www.amazon.co.jp/dp/4320112458/)
* [因果推論に関する各種資料](https://www.jaysong.net/post/causal_inference/)