---
title: "求める人物像"
date-modified: "`r Sys.Date()`"
toc: true
link-external-newwindow: true
link-external-icon: true
---

```{r}
#| include: false
```

## 1. 積極性

#### 費やした時間と成果は比例します

　ネットワーク分析で有名な[バラバシ先生](https://barabasi.com/)は、成功（success）のためには何度もチャレンジしていくことが重要であることを強調しています。大変面白い動画ですのでぜひご覧になってください（日本語字幕もあります）。

* [Albert-László Barabási: The real relationship between your age and your chance of success](https://embed.ted.com/talks/albert_laszlo_barabasi_the_real_relationship_between_your_age_and_your_chance_of_success)

> [I]f you keep trying, you could still succeed and succeed over and over.

　皆さんが<u>**スキルの習得に費やした時間と、実際に得られたスキルは必ず正の関係**</u>を持ちます。人によっては100を達成するために1時間を要する人もいれば、5時間を要する人もいるでしょう。スピードに差はあるかも知れませんが、時間とレベルは必ず比例します。体育や芸術などとは違って、<u>**データ分析に才能というものは存在しない**</u>と、宋は考えております。ただし、年45時間のゼミだけでデータ分析、リサーチデザインなどのスキル全て身につけられるとは期待しないでください。これの数倍、数十倍の時間が必要です。したがって、ゼミ外時間の活用が非常に重要です。特に夏休み・冬休みはスキルアップのための絶好の時期であり、他人と差を付けたいのなら休み期間がチャンスです。<u>**ゼミ外時間、そして夏休み・冬休みにも積極的に学習・研究活動に取り組む方を歓迎**</u>します。

　ゼミ生からの要望がありましたら、サブゼミとして分析ツール講習会の開催も検討します。また、2022年度は新型コロナで無理だと考えられますが、今後、方法論の合宿も行う可能性もあります。

#### たくさんの失敗を味わいましょう

　パソコンを触っていくと、何度もエラーメッセージが遭遇したり、自分が欲しい結果が得られない時もあるでしょう。人によってはエラーメッセージなんかに遭遇しない人もいるかも知れません。しかし、現場において最も重宝されるのはたくさんの失敗を経験した人です。<u>**成功の経験しかない人は、失敗の時の対応が苦手**</u>です。失敗しを繰り返し、それを克服していく過程そのものに大きな意味があります。失敗を恐れない方を歓迎します。

#### 分からないことを分からないまま放置しないように！

　これは非常に重要です。分からないことを放置した時点で成長は止まります。小説や漫画、ゲームなどストーリーが存在するあらゆるものにおいて、後の内容は前の内容に基づいています。これはほとんどの教科書、学術書、論文だけでなく、学習の過程にも共通しています。学習において**前の内容が分からないと後の内容は分かりません。**分からないものを放置して進むと、必ず壁に遭遇し、そこで頓挫します。そしてもう一度最初に戻らざるを得なくなります。限られた時間においてこれは大きな損失です。

　疑問点をその場で解決することは、今は面倒かも知れません。しかし、2年間のゼミを考えると、これは時間の節約になります。特に2年目は就活なので学習時間が限られてきます。分からないことがあれば他の入門書・教科書、インターネット検索、最終的には担当教員との相談で解決しましょう。

#### 海外の論文を読みましょう

　輪読の際、基本的には日本語の文献（本・論文）を読みますが、**必要に応じて英語の文献も読む**必要があります。多くの学生が「XXに関する先行研究は存在しない。だから本稿ではXXについて分析を行う」と書いたりしますが、これは高確率で誤りです。ほとんど研究の場合、先行研究が存在します。存在を知らないだけです。たまに、天才的な発想で誰も思いつかなかったテーマを見つけるケースも稀にありますが、本当に稀（SSR）です。また、本当に先行研究が存在しないとしてもそれは現実的に研究の遂行が困難なテーマか、学術的にあまり意味のないテーマである可能性が高いです。皆さんが何かのテーマを決めたらそれに関連する文献は必ずあると考えても良いでしょう。そして、それらのほとんどは英語で書かれています。英語の論文を一回も読んだことのない学生にとって、英語の論文は苦痛でしかないでしょう。しかし、英語の論文はかなり構成が論理的であるため、言語の側面を除けば逆に読みやすいです。また、最近は機械翻訳の精度も非常に高く、こちらも合わせて使うことも可能でしょう（ただし、機械翻訳を盲信してはいけません。たまにとんでもない結果を返したりします）。卒業研究に取り組むまでたくさんの論文を読むことになりますが、日本語の文献だけでなく、海外の文献にも挑戦する方を歓迎します。

#### サークル活動について

　サークル活動と並行することは全く問題ございませんが、**サークル活動の配慮は致しません**。欠席に関しましては公欠扱いが可能でしたら公欠としますが、学習やグループワークにおける遅れは全て自己責任となります。欠席された分、自分で遅れを補う積極性が求められます。

## 2. コミュニケーション能力

　多くの学問分野において共同作業、つまり「共著」が一般化しています。これまで「共著」といえば理系のイメージが強く、文系は「単著」文化だと認識されてきました。総合情報学部は文理融合学部です。共著も単著も体験して頂きます。文系においてもごく一部の分野を除き、共著文化が定着しつつあります。私が携わっている政治学も例外ではありません。共同作業においてコミュニケーション能力が必須です。これは「他人と楽しくしゃべる」ことを意味するわけではありません。ここでのコミュ力とは何かがあったら皆と相談する、途中経過を共有する、他人からのフィードバックに耳を傾けるといったものを指します。共同研究においてこれらは非常に大事です。

　最終的には単著で卒業論文を執筆することになりますが、一人で執筆するとしてもコミュニケーション能力は重要です。研究のプロである研究者たちも一つの論文を出すまで何回も研究会・学会で報告したり、他研究者との相談を通じてフィードバックをもらいます。単著は独り善がりの研究になりやすい故、このようなコミュニケーションは非常に重要です。

　宋にとって日本語は外国語ですし、文法も、アクセントもめちゃくちゃです。それでも人とコミュニケーションをとっています。上手に喋るに越したことはありませんが、大事なのは<u>**発信と意見の受け入れを恐れない態度**</u>です。

## 3. 探求力と知的好奇心

　何かを継続していくには、そこから何かの意味を見出さなければなりません。以下の動画を御覧ください（日本語字幕もあります）。行動経済学者の[アリエリー先生](https://danariely.com/)のTED公演動画です。

* [Dan Ariely: What makes us feel good about our work?](https://embed.ted.com/talks/dan_ariely_what_makes_us_feel_good_about_our_work)

　<u>**データ分析手法を身につける過程は退屈な作業の連続です。継続していくためには、目標が必要です。**</u>単に「データ分析に慣れたい/上達したい」という曖昧な目標だけでは、途中で諦めやすいです。そもそも「慣れ」や「上達」は主観的なものだからです。やはり「XXを明らかにしたい」といった具体的な問いがあって、その問いに答えるためのスキルとしてデータ分析を習得していく必要があります。むろん、美しいコードを作成したり、綺麗なグラフを作ることが目的の方には、これ自体が目的ですので、良いでしょう（宋がこのタイプの人間です）。あるいは、データ分析に関する資格（統計検定など）の取得のような目標も良いかも知れません。「XXを達成したら絶対うれしい！」といった具体的な目標を持つ方を歓迎します。